<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeaderMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderMenuRepository extends EntityRepository
{
}